// The Commit Comparison host: the extension's own page, generated by the stubbed generator and
// driven over the graph_request channel - the loading page first, the data page once the
// backend answers, and the page's file-diff request answered back into the frame.

import { describe, expect, test, vi } from 'vitest';

import { CompareHost } from '../src/graphHost';
import { THEME_EVENT, updateSetting } from '../src/settings';
import { backend } from './tauriMock';

const generated: Record<string, unknown>[] = [];

vi.mock('@tauri-apps/api/core', async () => ({ invoke: (await import('./tauriMock')).invoke }));

function stubGenerator(): void {
	(window as unknown as { GitGraphCompare?: unknown }).GitGraphCompare = {
		buildComparePage: (options: Record<string, unknown>) => {
			generated.push(options);
			return '<!DOCTYPE html><html><head><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'nonce-testnonce123\';"><script nonce="testnonce123">page()</script></head><body>page</body></html>';
		}
	};
}

describe('CompareHost', () => {
	test('shows the loading page, then the page built with the fetched comparison data', async () => {
		stubGenerator();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [{ oldFilePath: 'a.txt', newFilePath: 'a.txt', type: 'M', additions: 1, deletions: 2 }], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: { abc12345: { hash: 'abc12345', author: 'A', email: 'a@b.c', date: 1, message: 'm' } }, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', hash: 'abc12345', count: 3 };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const openDiff = vi.fn();
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: 'def67890', singleCommit: false }, { openDiff });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		// The loading page comes first; the data page carries the fetched changes and count.
		expect(generated[0]!['loading']).toBe(true);
		expect(generated[1]!['loading']).toBeUndefined();
		expect(generated[1]!['fileChanges']).toEqual([{ oldFilePath: 'a.txt', newFilePath: 'a.txt', type: 'M', additions: 1, deletions: 2 }]);
		expect(generated[1]!['commitsBetween']).toBe(3);
		// The shim rides under the page's own nonce, ahead of the page's scripts.
		const frame = container.querySelector('iframe')!;
		expect(frame.getAttribute('srcdoc')).toContain('nonce="testnonce123"');
		expect(frame.getAttribute('srcdoc')).toContain('acquireVsCodeApi');

		// A page request is answered over the channel and posted back into the frame's window;
		// the host filters on the message's source, so the event claims the frame's window.
		const frameWindow = frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'getFileDiff', index: 0 } } }));
		await vi.waitFor(() => expect(postSpy).toHaveBeenCalled());
		expect(backend.callsTo('graph_request').at(-1)!['message']).toMatchObject({ command: 'getCommitFileDiff' });
		expect(postSpy.mock.calls.at(-1)![0]).toMatchObject({ command: 'fileDiff', index: 0 });
		postSpy.mockRestore();
		host.dispose();
		container.remove();
	});

	test('settles the pending line counts of an uncommitted comparison (the page never asks for them)', async () => {
		generated.length = 0;
		stubGenerator();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [{ oldFilePath: 'a.txt', newFilePath: 'a.txt', type: 'M', additions: null, deletions: null }], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: {}, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', count: 2 };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: '*', singleCommit: false }, { openDiff: vi.fn() });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		const frameWindow = container.querySelector('iframe')!.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);

		// The page's first message proves its listener is up; the host settles the "+/-" rows.
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'getFileDiff', index: 0 } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'lineCounts')).toBe(true));
		const settle = postSpy.mock.calls.map((c) => c[0] as Record<string, unknown>).find((m) => m['command'] === 'lineCounts')!;
		expect(settle['counts']).toEqual({ 'a.txt': { additions: null, deletions: null } });
		// The engine is never asked for counts it cannot produce against the working tree.
		expect(backend.callsTo('graph_request').some((c) => (c['message'] as Record<string, unknown>)['command'] === 'commitFileCounts')).toBe(false);

		// A direct requestCounts is answered too, never left hanging.
		postSpy.mockClear();
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'requestCounts', paths: ['a.txt'] } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'lineCounts')).toBe(true));
		expect(backend.callsTo('graph_request').some((c) => (c['message'] as Record<string, unknown>)['command'] === 'commitFileCounts')).toBe(false);
		host.dispose();
		container.remove();
	});

	test('answers requestCounts with the backend counts for a committed comparison', async () => {
		generated.length = 0;
		stubGenerator();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [{ oldFilePath: 'a.txt', newFilePath: 'a.txt', type: 'M', additions: null, deletions: null }], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: {}, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', count: 2 };
				case 'commitFileCounts':
					return { command: 'commitFileCounts', counts: { 'a.txt': { additions: 3, deletions: 1 } }, error: null };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: 'def67890', singleCommit: false }, { openDiff: vi.fn() });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		const frameWindow = container.querySelector('iframe')!.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'requestCounts', paths: ['a.txt'] } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'lineCounts')).toBe(true));
		expect(backend.callsTo('graph_request').map((c) => c['message'] as Record<string, unknown>).find((m) => m['command'] === 'commitFileCounts'))
			.toMatchObject({ from: 'abc12345', to: 'def67890', paths: ['a.txt'] });
		expect(postSpy.mock.calls.map((c) => c[0] as Record<string, unknown>).find((m) => m['command'] === 'lineCounts')!['counts'])
			.toEqual({ 'a.txt': { additions: 3, deletions: 1 } });
		host.dispose();
		container.remove();
	});

	test('is themed by the shell from the first paint and follows theme switches', async () => {
		generated.length = 0;
		stubGenerator();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: {}, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', count: 0 };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: 'def67890', singleCommit: false }, { openDiff: vi.fn() });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		// The generated page's CSS is all var(--vscode-*) tokens: the theme's token sheet rides
		// under the page's head from the first paint, and the vscode-* class gates its
		// light-theme overrides onto the body.
		const frame = container.querySelector('iframe')!;
		const srcdoc = frame.getAttribute('srcdoc')!;
		expect(srcdoc).toContain('id="ggs-host-theme"');
		expect(srcdoc).toContain('href="/theme/dark-modern.css"');
		expect(srcdoc).toContain('<body class="vscode-dark">');

		// A theme switch swaps the sheet and the classes in the live page (no re-render: the
		// page's styles are all variables). The event bubbles: the host listens on window.
		updateSetting('theme', 'light-modern');
		document.dispatchEvent(new CustomEvent(THEME_EVENT, { bubbles: true }));
		const doc = frame.contentDocument!;
		expect(doc.documentElement.classList.contains('vscode-light')).toBe(true);
		expect(doc.body!.classList.contains('vscode-light')).toBe(true);
		expect((doc.getElementById('ggs-host-theme') as HTMLLinkElement).getAttribute('href')).toBe('/theme/light-modern.css');
		updateSetting('theme', 'dark-modern');
		host.dispose();
		container.remove();
	});
});
