// The Git Graph comparison hosts: the extension's own pages, generated by the stubbed
// generators and driven over the graph_request channel - the loading page first, the data page
// once the backend answers, the page's file-diff request answered back into the frame, and the
// binary files' hex / picture area answered through the extension's own session machinery.

import { describe, expect, test, vi } from 'vitest';

import { BinaryCompareHost, CompareHost, type BinaryCompareInput } from '../src/graphHost';
import { THEME_EVENT, updateSetting } from '../src/settings';
import { backend } from './tauriMock';

const generated: Record<string, unknown>[] = [];

vi.mock('@tauri-apps/api/core', async () => ({ invoke: (await import('./tauriMock')).invoke }));

function stubGenerator(): void {
	(window as unknown as { GitGraphCompare?: unknown }).GitGraphCompare = {
		buildComparePage: (options: Record<string, unknown>) => {
			generated.push(options);
			return '<!DOCTYPE html><html><head><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'nonce-testnonce123\';"><script nonce="testnonce123">page()</script></head><body>page</body></html>';
		}
	};
}

/** The hex-session machinery compare.js serves, stubbed at the same boundary the hosts call
 *  it: the sessions it "creates" record the inputs, and its responders post canned replies. */
const createdSessions: { dataSource: { spawnGitStream?(args: string[], repo: string): unknown }; repo: string; fromHash: string; toHash: string; file: Record<string, unknown> }[] = [];
const sessions: { onSections: ((sections: unknown, error: string | null) => void) | null; disposed: boolean; dispose(): void }[] = [];

function stubMachinery(): void {
	const machinery = (window as unknown as { GitGraphCompare?: Record<string, unknown> }).GitGraphCompare as Record<string, unknown>;
	machinery['createHexSession'] = (dataSource: { spawnGitStream?(args: string[], repo: string): unknown }, repo: string, fromHash: string, toHash: string, file: Record<string, unknown>) => {
		createdSessions.push({ dataSource, repo, fromHash, toHash, file });
		const session = { onSections: null, disposed: false, dispose: () => { session.disposed = true; } };
		sessions.push(session);
		return session;
	};
	machinery['wireHexSession'] = (session: { onSections: unknown }, index: number, post: (message: Record<string, unknown>) => void) => {
		session.onSections = (sections: unknown, error: string | null) => post({ command: 'hexMap', index, sections, error });
	};
	machinery['respondHexInfo'] = async (_session: unknown, index: number, bytesPerRow: number, post: (message: Record<string, unknown>) => void) => post({ command: 'hexInfo', index, bytesPerRow, error: null });
	machinery['respondHexRows'] = async (_session: unknown, index: number, start: number, _count: number, post: (message: Record<string, unknown>) => void) => post({ command: 'hexRows', index, start, rows: [], error: null });
	machinery['respondImageData'] = async (_session: unknown, index: number, _file: unknown, post: (message: Record<string, unknown>) => void) => post({ command: 'imageData', index, error: null, oldData: null, newData: null, oldSize: 0, newSize: 0 });
	machinery['respondCopyToClipboard'] = async (post: (message: Record<string, unknown>) => void, type: string, _data: string) => post({ command: 'copyToClipboard', type, error: null });
}

describe('CompareHost', () => {
	test('shows the loading page, then the page built with the fetched comparison data', async () => {
		stubGenerator();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [{ oldFilePath: 'a.txt', newFilePath: 'a.txt', type: 'M', additions: 1, deletions: 2 }], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: { abc12345: { hash: 'abc12345', author: 'A', email: 'a@b.c', date: 1, message: 'm' } }, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', hash: 'abc12345', count: 3 };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const openDiff = vi.fn();
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: 'def67890', singleCommit: false }, { openDiff, openBinaryCompare: vi.fn() });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		// The loading page comes first; the data page carries the fetched changes and count.
		expect(generated[0]!['loading']).toBe(true);
		expect(generated[1]!['loading']).toBeUndefined();
		expect(generated[1]!['fileChanges']).toEqual([{ oldFilePath: 'a.txt', newFilePath: 'a.txt', type: 'M', additions: 1, deletions: 2 }]);
		expect(generated[1]!['commitsBetween']).toBe(3);
		// The shim rides under the page's own nonce, ahead of the page's scripts.
		const frame = container.querySelector('iframe')!;
		expect(frame.getAttribute('srcdoc')).toContain('nonce="testnonce123"');
		expect(frame.getAttribute('srcdoc')).toContain('acquireVsCodeApi');

		// A page request is answered over the channel and posted back into the frame's window;
		// the host filters on the message's source, so the event claims the frame's window.
		const frameWindow = frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'getFileDiff', index: 0 } } }));
		await vi.waitFor(() => expect(postSpy).toHaveBeenCalled());
		expect(backend.callsTo('graph_request').at(-1)!['message']).toMatchObject({ command: 'getCommitFileDiff' });
		expect(postSpy.mock.calls.at(-1)![0]).toMatchObject({ command: 'fileDiff', index: 0 });
		postSpy.mockRestore();
		host.dispose();
		container.remove();
	});

	test('settles the pending line counts of an uncommitted comparison (the page never asks for them)', async () => {
		generated.length = 0;
		stubGenerator();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [{ oldFilePath: 'a.txt', newFilePath: 'a.txt', type: 'M', additions: null, deletions: null }], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: {}, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', count: 2 };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: '*', singleCommit: false }, { openDiff: vi.fn(), openBinaryCompare: vi.fn() });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		const frameWindow = container.querySelector('iframe')!.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);

		// The page's first message proves its listener is up; the host settles the "+/-" rows.
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'getFileDiff', index: 0 } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'lineCounts')).toBe(true));
		const settle = postSpy.mock.calls.map((c) => c[0] as Record<string, unknown>).find((m) => m['command'] === 'lineCounts')!;
		expect(settle['counts']).toEqual({ 'a.txt': { additions: null, deletions: null } });
		// The engine is never asked for counts it cannot produce against the working tree.
		expect(backend.callsTo('graph_request').some((c) => (c['message'] as Record<string, unknown>)['command'] === 'commitFileCounts')).toBe(false);

		// A direct requestCounts is answered too, never left hanging.
		postSpy.mockClear();
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'requestCounts', paths: ['a.txt'] } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'lineCounts')).toBe(true));
		expect(backend.callsTo('graph_request').some((c) => (c['message'] as Record<string, unknown>)['command'] === 'commitFileCounts')).toBe(false);
		host.dispose();
		container.remove();
	});

	test('answers requestCounts with the backend counts for a committed comparison', async () => {
		generated.length = 0;
		stubGenerator();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [{ oldFilePath: 'a.txt', newFilePath: 'a.txt', type: 'M', additions: null, deletions: null }], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: {}, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', count: 2 };
				case 'commitFileCounts':
					return { command: 'commitFileCounts', counts: { 'a.txt': { additions: 3, deletions: 1 } }, error: null };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: 'def67890', singleCommit: false }, { openDiff: vi.fn(), openBinaryCompare: vi.fn() });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		const frameWindow = container.querySelector('iframe')!.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'requestCounts', paths: ['a.txt'] } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'lineCounts')).toBe(true));
		expect(backend.callsTo('graph_request').map((c) => c['message'] as Record<string, unknown>).find((m) => m['command'] === 'commitFileCounts'))
			.toMatchObject({ from: 'abc12345', to: 'def67890', paths: ['a.txt'] });
		expect(postSpy.mock.calls.map((c) => c[0] as Record<string, unknown>).find((m) => m['command'] === 'lineCounts')!['counts'])
			.toEqual({ 'a.txt': { additions: 3, deletions: 1 } });
		host.dispose();
		container.remove();
	});

	test('is themed by the shell from the first paint and follows theme switches', async () => {
		generated.length = 0;
		stubGenerator();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: {}, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', count: 0 };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: 'def67890', singleCommit: false }, { openDiff: vi.fn(), openBinaryCompare: vi.fn() });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		// The generated page's CSS is all var(--vscode-*) tokens: the theme's token sheet rides
		// under the page's head from the first paint, and the vscode-* class gates its
		// light-theme overrides onto the body.
		const frame = container.querySelector('iframe')!;
		const srcdoc = frame.getAttribute('srcdoc')!;
		expect(srcdoc).toContain('id="ggs-host-theme"');
		expect(srcdoc).toContain('href="/theme/dark-modern.css"');
		expect(srcdoc).toContain('<body class="vscode-dark">');

		// A theme switch swaps the sheet and the classes in the live page (no re-render: the
		// page's styles are all variables). The event bubbles: the host listens on window.
		updateSetting('theme', 'light-modern');
		document.dispatchEvent(new CustomEvent(THEME_EVENT, { bubbles: true }));
		const doc = frame.contentDocument!;
		expect(doc.documentElement.classList.contains('vscode-light')).toBe(true);
		expect(doc.body!.classList.contains('vscode-light')).toBe(true);
		expect((doc.getElementById('ggs-host-theme') as HTMLLinkElement).getAttribute('href')).toBe('/theme/light-modern.css');
		updateSetting('theme', 'dark-modern');
		host.dispose();
		container.remove();
	});

	test('answers the page\'s binary-file hex area through the extension\'s own machinery', async () => {
		generated.length = 0;
		createdSessions.length = 0;
		sessions.length = 0;
		stubGenerator();
		stubMachinery();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [{ oldFilePath: 'logo.png', newFilePath: 'logo.png', type: 'M', additions: null, deletions: null }], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: {}, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', count: 1 };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: 'def67890', singleCommit: false, repo: 'C:\\repo' }, { openDiff: vi.fn(), openBinaryCompare: vi.fn() });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		const frameWindow = container.querySelector('iframe')!.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);

		// The page's binary area asks for the hex layout: a session is created through the
		// machinery with a spawnGitStream-capable DataSource over this comparison's ends, and
		// the responder's reply is posted straight back into the frame.
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'getHexInfo', index: 0, bytesPerRow: 16 } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'hexInfo')).toBe(true));
		expect(createdSessions.length).toBe(1);
		expect(typeof createdSessions[0]!.dataSource.spawnGitStream).toBe('function');
		expect(createdSessions[0]!.repo).toBe('C:\\repo');
		expect(createdSessions[0]!.fromHash).toBe('abc12345');
		expect(createdSessions[0]!.toHash).toBe('def67890');
		expect(createdSessions[0]!.file).toMatchObject({ oldFilePath: 'logo.png', type: 'M' });

		// Rows reuse the created session; the clipboard request is answered the same way.
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'getHexRows', index: 0, start: 0, count: 10 } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'hexRows')).toBe(true));
		expect(createdSessions.length).toBe(1);

		// Disposing the tab disposes every session it created.
		host.dispose();
		expect(sessions[0]!.disposed).toBe(true);
		postSpy.mockRestore();
		container.remove();
	});

	test('opens the extension\'s Binary Compare tab for the page\'s viewDiffBinary, with the comparison\'s own ends', async () => {
		generated.length = 0;
		stubGenerator();
		stubMachinery();
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			switch (message['command']) {
				case 'getCommitComparison':
					return { command: 'getCommitComparison', fileChanges: [{ oldFilePath: 'logo.png', newFilePath: 'logo.png', type: 'M', additions: null, deletions: null }], error: null };
				case 'getCommitSummaries':
					return { command: 'getCommitSummaries', summaries: {}, error: null };
				case 'countCommitsBefore':
					return { command: 'countCommitsBefore', count: 1 };
				default:
					return { command: message['command'], error: null };
			}
		});
		const container = document.createElement('div');
		document.body.appendChild(container);
		const openBinaryCompare = vi.fn();
		const host = new CompareHost(container, { fromHash: 'abc12345', toHash: 'def67890', singleCommit: false, repo: 'C:\\repo' }, { openDiff: vi.fn(), openBinaryCompare });
		await vi.waitFor(() => expect(generated.length).toBe(2));
		const frameWindow = container.querySelector('iframe')!.contentWindow!;
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggComparePage: { command: 'viewDiffBinary', index: 0 } } }));
		await vi.waitFor(() => expect(openBinaryCompare).toHaveBeenCalledTimes(1));
		// comparisonView.ts passes its own two ends to BinaryCompareView.open - un-resolved,
		// unlike the graph view's viewDiffBinary handler.
		expect(openBinaryCompare.mock.calls[0][0]).toEqual({
			repo: 'C:\\repo',
			fromHash: 'abc12345',
			toHash: 'def67890',
			file: { oldFilePath: 'logo.png', newFilePath: 'logo.png', type: 'M' }
		});
		host.dispose();
		container.remove();
	});
});

describe('BinaryCompareHost', () => {
	const binaryPages: Record<string, unknown>[] = [];

	function stubBinaryGenerator(): void {
		(window as unknown as { GitGraphBinaryCompare?: unknown }).GitGraphBinaryCompare = {
			buildBinaryComparePage: (options: Record<string, unknown>) => {
				binaryPages.push(options);
				return '<!DOCTYPE html><html><head><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'nonce-testnonce123\';"><script nonce="testnonce123">page()</script></head><body>binary page</body></html>';
			}
		};
	}

	const input: BinaryCompareInput = { repo: 'C:\\repo', fromHash: 'abc12345', toHash: 'def67890', file: { oldFilePath: 'assets/logo.png', newFilePath: 'assets/logo.png', type: 'M' } };

	test('hosts the extension\'s own page with the shim under its nonce, and drives it at index 0', async () => {
		binaryPages.length = 0;
		createdSessions.length = 0;
		sessions.length = 0;
		stubGenerator();
		stubMachinery();
		stubBinaryGenerator();
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new BinaryCompareHost(container, input);
		await vi.waitFor(() => expect(binaryPages.length).toBe(1));
		// The generator receives the file and both ends, exactly what the extension's own
		// BinaryCompareView.open builds its page from.
		expect(binaryPages[0]).toMatchObject({ fromHash: 'abc12345', toHash: 'def67890', filePath: 'assets/logo.png', file: { oldFilePath: 'assets/logo.png', type: 'M' } });
		const frame = container.querySelector('iframe')!;
		const srcdoc = frame.getAttribute('srcdoc')!;
		expect(srcdoc).toContain('nonce="testnonce123"');
		expect(srcdoc).toContain('__ggBinComparePage');
		expect(srcdoc).toContain('id="ggs-host-theme"');
		expect(srcdoc).toContain('<body class="vscode-dark">');

		// The page's first request creates the one session (index 0) and its reply is posted back.
		const frameWindow = frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggBinComparePage: { command: 'getHexInfo', index: 0, bytesPerRow: 8 } } }));
		await vi.waitFor(() => expect(postSpy.mock.calls.some((c) => (c[0] as Record<string, unknown>)['command'] === 'hexInfo')).toBe(true));
		expect(createdSessions.length).toBe(1);
		expect(createdSessions[0]!.fromHash).toBe('abc12345');
		expect((postSpy.mock.calls.find((c) => (c[0] as Record<string, unknown>)['command'] === 'hexInfo')![0] as Record<string, unknown>)['bytesPerRow']).toBe(8);

		host.dispose();
		expect(sessions[0]!.disposed).toBe(true);
		postSpy.mockRestore();
		container.remove();
	});

	test('releases the materialized blob temp files when the tab goes away', async () => {
		binaryPages.length = 0;
		createdSessions.length = 0;
		sessions.length = 0;
		stubGenerator();
		// The "machinery" asks for the blob's size through the DataSource the host hands it,
		// which materializes the revision's blob to a temp file over the backend.
		(window as unknown as { GitGraphCompare?: Record<string, unknown> }).GitGraphCompare!['createHexSession'] =
			(dataSource: { spawnGitStream?(args: string[], repo: string): unknown }) => {
				dataSource.spawnGitStream?.(['cat-file', '-s', 'abc12345:assets/logo.png'], 'C:\\repo');
				const session = { onSections: null, disposed: false, dispose: () => { session.disposed = true; } };
				sessions.push(session);
				return session;
			};
		stubBinaryGenerator();
		const temp = 'C:\\Temp\\git-graph-studio-hex-4242-7\\logo.png';
		backend.on('materialize_revision_file', () => temp);
		backend.on('file_probe', () => ({ size: 5, binary: true, longLines: false }));
		const container = document.createElement('div');
		document.body.appendChild(container);
		const host = new BinaryCompareHost(container, input);
		await vi.waitFor(() => expect(binaryPages.length).toBe(1));
		const frameWindow = container.querySelector('iframe')!.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __ggBinComparePage: { command: 'getHexInfo', index: 0, bytesPerRow: 16 } } }));
		await vi.waitFor(() => expect(backend.callsTo('materialize_revision_file').length).toBe(1));
		expect(backend.callsTo('materialize_revision_file')[0]).toMatchObject({ repo: 'C:\\repo', revision: 'abc12345', path: 'assets/logo.png' });
		host.dispose();
		await vi.waitFor(() => expect(backend.callsTo('discard_temp_blob').length).toBe(1));
		expect(backend.callsTo('discard_temp_blob')[0]).toMatchObject({ path: temp });
		postSpy.mockRestore();
		container.remove();
	});
});
