// The Git Graph view's mount: the view page is the extension's own, generated by its
// getHtmlForWebview (served as gitgraph/viewpage.js) and composed with the host environment
// by graphPreload.ts - the theme tokens, the acquireVsCodeApi protocol shim, the deferred
// script loading. The repository set the view's dropdown offers is the open repository plus
// its initialised submodules.

import { beforeEach, describe, expect, it, vi } from 'vitest';

import { GraphHost, type GraphHostDelegate } from '../src/graphHost';
import { claimGraphPreload, startGraphPreload } from '../src/graphPreload';
import { THEME_EVENT, updateSetting } from '../src/settings';
import { backend } from './tauriMock';
import { flush } from './helpers';

const delegate: GraphHostDelegate = {
	openFile: () => undefined,
	openDiff: () => undefined,
	openFileAtRevision: () => undefined,
	openCompareTab: () => undefined,
	openBinaryCompare: () => undefined,
	showSourceControl: () => undefined,
	revealTerminal: () => undefined,
	runInTerminal: () => undefined,
	repoChanged: () => undefined
};

/** The extension's own view page generator, stubbed at the boundary graphPreload.ts calls it:
 *  the fixture page carries a CSP nonce and the two media script tags the composer lifts out
 *  (the markdown renderer and the view bundle), and every generation is recorded. */
const viewPages: Record<string, unknown>[] = [];

function stubViewPage(): void {
	(window as unknown as { GitGraphViewPage?: unknown }).GitGraphViewPage = {
		buildViewPage: (options: Record<string, unknown>) => {
			viewPages.push(options);
			return '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">' +
				'<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'nonce-testnonce123\';">' +
				'</head><body><div id="view"></div>' +
				'<script nonce="testnonce123">var initialState = {};</script>' +
				'<script nonce="testnonce123" src="/gitgraph/markdown-it.min.js?v=1"></script>' +
				'<script nonce="testnonce123" src="/gitgraph/out.min.js?v=1"></script>' +
				'</body></html>';
		}
	};
}

describe('graph assets', () => {
	beforeEach(() => {
		localStorage.clear();
		sessionStorage.clear();
		viewPages.length = 0;
		stubViewPage();
		backend.on('repo_submodules', () => []);
	});

	it('generates the extension\'s own page into the frame, composed with the host environment', async () => {
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		expect(host.loaded).toBe(true);
		await flush(10);
		// The page came from the extension's own generator, over the repository set.
		expect(viewPages.length).toBe(1);
		expect(Object.keys(viewPages[0]!['repos'] as Record<string, unknown>)).toEqual(['C:\\repo']);
		expect(viewPages[0]!['lastActiveRepo']).toBe('C:\\repo');
		// The composition: the theme sheet ahead of everything, the acquireVsCodeApi protocol
		// shim under the page's own nonce, the theme kind on the body - and the media scripts
		// lifted out for the shim to load after the theme has applied.
		const srcdoc = host.frame.getAttribute('srcdoc')!;
		expect(srcdoc).toContain('nonce="testnonce123"');
		expect(srcdoc).toContain('__studioGraphRequest');
		expect(srcdoc).toContain('id="ggs-host-theme"');
		expect(srcdoc).toContain('<body class="vscode-dark"');
		expect(srcdoc).not.toContain('src="/gitgraph/out.min.js?v=1"');
		expect(srcdoc).toContain('/gitgraph/out.min.js?v=1'); // carried in the shim's config
	});

	it('feeds the preloaded page its repositories instead of regenerating it', async () => {
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.preload('C:\\repo');
		await flush(10);
		// The page starts in the background with the one repository known up front.
		expect(viewPages.length).toBe(1);
		expect(viewPages[0]!['lastActiveRepo']).toBe('C:\\repo');
		expect(Object.keys(viewPages[0]!['repos'] as Record<string, unknown>)).toEqual(['C:\\repo']);
		expect(host.frame.getAttribute('srcdoc')).toContain('nonce="testnonce123"');
		// The page reports its bundle ran (see the shim): the mount hands the live page
		// the full repository set over loadRepos rather than paying the regeneration.
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphBooted: true } }));
		host.load('C:\\repo');
		await flush(10);
		const sent = postSpy.mock.calls
			.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
			.filter((message) => message['command'] === 'loadRepos')[0];
		expect(sent).toBeDefined();
		expect(Object.keys(sent['repos'] as Record<string, unknown>)).toContain('C:\\repo');
		expect(sent['lastActiveRepo']).toBe('C:\\repo');
	});

	it('regenerates the page when the preloaded page reports its bundle failed', async () => {
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.preload('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		// A page whose bundle did not run must not be talked to: the mount regenerates the
		// page instead of feeding the dead one.
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphBooted: false } }));
		host.load('C:\\repo');
		await flush(10);
		expect(viewPages.length).toBe(2);
		expect(host.frame.getAttribute('srcdoc')).toContain('nonce="testnonce123"');
		expect(postSpy.mock.calls.filter((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse['command'] === 'loadRepos').length).toBe(0);
	});

	it('claims the splash-warmed frame and mounts it without a regeneration', async () => {
		// The splash warmer composes the page for the launch's folder before the workbench
		// exists; the host adopts the frame when it comes up.
		backend.on('boot_context', () => ({ file: null, actions: [], repo: 'C:\\repo' }));
		startGraphPreload();
		await flush(10);
		const host = new GraphHost(delegate);
		try {
			document.body.appendChild(host.element);
			// One claim only: the frame is the warmed one, back in the layout.
			expect(claimGraphPreload()).toBeNull();
			expect(host.frame.getAttribute('srcdoc')).toContain('nonce="testnonce123"');
			expect(host.frame.style.display).toBe('');
			// The page finished booting while the workbench was still loading (its window
			// says so - the shim sets it): the mount talks to the live page directly.
			(host.frame.contentWindow as unknown as { __ggViewBooted: boolean }).__ggViewBooted = true;
			const postSpy = vi.spyOn(host.frame.contentWindow!, 'postMessage').mockImplementation(() => undefined);
			host.load('C:\\repo');
			await flush(10);
			const sent = postSpy.mock.calls
				.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
				.filter((message) => message['command'] === 'loadRepos')[0];
			expect(sent).toBeDefined();
			expect(sent['lastActiveRepo']).toBe('C:\\repo');
		} finally {
			claimGraphPreload();
		}
	});

	it('offers the open repository and its initialised submodules to the view', async () => {
		backend.on('repo_submodules', () => ['C:\\repo\\sub\\dep', 'C:\\repo\\vendor\\lib']);
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		expect(viewPages.length).toBe(1);
		expect(Object.keys(viewPages[0]!['repos'] as Record<string, unknown>).sort()).toEqual(['C:\\repo', 'C:\\repo\\sub\\dep', 'C:\\repo\\vendor\\lib']);

		// A loadRepos request from the view re-reads the set (a submodule may have been
		// initialised since) and answers with it.
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: { command: 'loadRepos' } } }));
		await flush(10);
		const sent = postSpy.mock.calls.map((call) => call[0] as { __studioGraphResponse: Record<string, unknown> })
			.filter((message) => message.__studioGraphResponse['command'] === 'loadRepos')
			.map((message) => message.__studioGraphResponse)[0];
		expect(Object.keys(sent['repos'] as Record<string, unknown>).sort()).toEqual(['C:\\repo', 'C:\\repo\\sub\\dep', 'C:\\repo\\vendor\\lib']);
		expect(sent['lastActiveRepo']).toBe('C:\\repo');
	});

	it('switches the view to a submodule - the Source Control view\'s per-repository graph icon', async () => {
		backend.on('repo_submodules', () => ['C:\\repo\\sub\\dep']);
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		host.switchRepo('C:\\repo\\sub\\dep');
		await flush(10);
		const sent = postSpy.mock.calls
			.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
			.filter((message) => message['command'] === 'loadRepos')[0];
		// The loadRepos response the view's own dropdown switch produces: the repository set,
		// the new repository as the active one, and a loadViewTo that names it.
		expect(Object.keys(sent['repos'] as Record<string, unknown>)).toContain('C:\\repo\\sub\\dep');
		expect(sent['lastActiveRepo']).toBe('C:\\repo\\sub\\dep');
		expect(sent['loadViewTo']).toEqual({ repo: 'C:\\repo\\sub\\dep' });
		// The host stays in step: a later loadRepos request from the view is answered with the
		// switched repository as the active one.
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: { command: 'loadRepos' } } }));
		await flush(10);
		const followUp = postSpy.mock.calls
			.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
			.filter((message) => message['command'] === 'loadRepos')
			.at(-1)!;
		expect(followUp['lastActiveRepo']).toBe('C:\\repo\\sub\\dep');

		// A repository outside the set is not switched to, and a repeat switch posts nothing.
		host.switchRepo('C:\\elsewhere');
		await flush(10);
		expect(postSpy.mock.calls.filter((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse['command'] === 'loadRepos').length).toBe(2);
	});

	it('lands a repository switch that raced the load on the freshly mounted view', async () => {
		backend.on('repo_submodules', () => ['C:\\repo\\sub\\dep']);
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		host.switchRepo('C:\\repo\\sub\\dep'); // before the mount's repository read settles
		await flush(10);
		expect(viewPages.length).toBe(1);
		expect(viewPages[0]!['lastActiveRepo']).toBe('C:\\repo\\sub\\dep');
	});

	it('opens a diff from a submodule against that submodule, not the open repository', async () => {
		const openDiff = vi.fn();
		const host = new GraphHost({ ...delegate, openDiff });
		document.body.appendChild(host.element);
		host.load('C:\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'viewDiff', repo: 'C:\repo\dep', fromHash: 'abc123def', toHash: 'abc123def',
			type: 'M', oldFilePath: 'lib.js', newFilePath: 'lib.js'
		} } }));
		await flush(10);
		expect(openDiff).toHaveBeenCalledTimes(1);
		const diff = openDiff.mock.calls[0][0] as { repo?: string; binaryNotice?: boolean; left: { revision: string } };
		expect(diff.repo).toBe('C:\repo\dep');
		expect(diff.left.revision).toBe('abc123def^');
		// A Git Graph diff whose sides turn out binary opens the diff editor's binary
		// placeholder, exactly what the native editor VS Code opens shows - never a
		// substituted view of the app's own.
		expect(diff.binaryNotice).toBe(true);
	});

	it('opens a binary file\'s comparison as the extension does - the Binary Compare tab, no response', async () => {
		// The webview sends `viewDiffBinary` once it already knows a file is binary; the
		// extension host opens its standalone Binary Compare tab with the left side resolved
		// exactly as its viewDiff resolves it, and sends no response. The shell keeps both
		// halves of that contract - the tab it opens is the extension's own page.
		const openBinaryCompare = vi.fn();
		const host = new GraphHost({ ...delegate, openBinaryCompare });
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const posted = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'viewDiffBinary', repo: 'C:\\repo', fromHash: 'abc12345', toHash: 'def67890',
			type: 'M', oldFilePath: 'archive.bin', newFilePath: 'archive.bin'
		} } }));
		await flush(10);
		expect(openBinaryCompare).toHaveBeenCalledTimes(1);
		expect(openBinaryCompare.mock.calls[0][0]).toEqual({
			repo: 'C:\\repo',
			// resolveDiffFromHash: different ends, so the left side is the from hash as-is.
			fromHash: 'abc12345',
			toHash: 'def67890',
			file: { oldFilePath: 'archive.bin', newFilePath: 'archive.bin', type: 'M' }
		});
		// The extension never answers viewDiffBinary (its Binary Compare tab just opens); the
		// webview has no handler for a response.
		expect(posted).not.toHaveBeenCalled();
	});

	it('resolves the left side of a same-commit binary comparison to its first parent', async () => {
		const openBinaryCompare = vi.fn();
		const host = new GraphHost({ ...delegate, openBinaryCompare });
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'viewDiffBinary', repo: 'C:\\repo', fromHash: '1234abcd', toHash: '1234abcd',
			type: 'M', oldFilePath: 'a.png', newFilePath: 'a.png'
		} } }));
		await flush(10);
		// resolveDiffFromHash(from, to) with from === to gives "<from>^" - the commit's parent.
		expect(openBinaryCompare.mock.calls[0][0]['fromHash']).toBe('1234abcd^');
	});

	it('keys a code review to the repository the request names, so a submodule review is found', async () => {
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			return { command: message['command'], commitDetails: {}, codeReview: null, error: null };
		});
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		// The view is switched to the submodule: the review starts and is looked up there.
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'startCodeReview', repo: 'C:\\repo\\sub', id: 'abc123', commitHash: 'abc123', compareWithHash: null, files: ['f.txt']
		} } }));
		await flush(10);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'commitDetails', repo: 'C:\\repo\\sub', commitHash: 'abc123'
		} } }));
		await flush(10);
		const posted = postSpy.mock.calls
			.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
			.filter((message) => message['command'] === 'commitDetails')
			.at(-1)!;
		expect(posted['codeReview']).toMatchObject({ id: 'abc123' });
	});

	it('shows the extension\'s own empty page for a folder without a repository', async () => {
		// What VS Code shows: the extension's own no-repository page (its rescan button
		// included), not a placeholder of the app's own.
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\plain', false);
		expect(host.loaded).toBe(false);
		await flush(10);
		expect(viewPages.length).toBe(1);
		expect(viewPages[0]!['repos']).toEqual({});
		expect(viewPages[0]!['lastActiveRepo']).toBeNull();
		const srcdoc = host.frame.getAttribute('srcdoc')!;
		expect(srcdoc).toContain('nonce="testnonce123"');

		// The empty page's rescan button reached the host; with still no repository nothing
		// is posted (no bundle runs there to take it) and the page stays as generated. A
		// running page (the settings widget's rescan) takes the fresh set instead.
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: { command: 'rescanForRepos', repo: 'C:\\plain' } } }));
		await flush(10);
		expect(viewPages.length).toBe(1);
		expect(postSpy).not.toHaveBeenCalled();
		(frameWindow as unknown as { __ggViewBooted: boolean }).__ggViewBooted = true;
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: { command: 'rescanForRepos', repo: 'C:\\plain' } } }));
		await flush(10);
		expect(postSpy.mock.calls.some((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse['command'] === 'loadRepos')).toBe(true);

		// Loading a repository afterwards generates the full page.
		host.load('C:\\repo');
		await flush(10);
		expect(viewPages.at(-1)!['repos']).toMatchObject({ 'C:\\repo': expect.anything() });
	});

	it('replaces the page on a reload and blanks the frame on unload', async () => {
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		host.load('C:\\other');
		await flush(10);
		// A folder switch regenerates the extension's page for the new repository.
		expect(viewPages.length).toBe(2);
		expect(Object.keys(viewPages[1]!['repos'] as Record<string, unknown>)).toEqual(['C:\\other']);
		expect(host.frame.getAttribute('srcdoc')).toContain('nonce="testnonce123"');
		host.unload();
		expect(host.frame.srcdoc).toBe('');
		expect(host.frame.src).toContain('about:blank');
		expect(host.loaded).toBe(false);
	});

	it('drops the view\'s persisted state on a repository switch, and keeps it on a reload', async () => {
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		// What the view persists through its own shim (graphPreload.ts): the repository it last
		// showed, and where it was scrolled to.
		sessionStorage.setItem('ggstudio.viewState', JSON.stringify({ currentRepo: 'C:\\repo', scrollTop: 120 }));
		// A reload of the same folder keeps it - the reader's place survives an external reload.
		host.load('C:\\repo');
		await flush(10);
		expect(JSON.parse(sessionStorage.getItem('ggstudio.viewState')!)).toMatchObject({ currentRepo: 'C:\\repo' });
		// A switch must not: on boot the page offers the persisted repository back as a
		// loadViewTo, and a repository the new set does not contain makes the view show its
		// "not currently included in Git Graph" error naming the previous repository.
		host.load('D:\\other');
		await flush(10);
		expect(sessionStorage.getItem('ggstudio.viewState')).toBeNull();
	});

	it('follows a theme switch into the view frame without a reload', async () => {
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		// jsdom's never-navigated iframe document has no html/head/body; a real browser always
		// provides them (the generated page carries all three), so the skeleton exists before the theme
		// switch the way the real page's does.
		const doc = host.frame.contentDocument!;
		if (!doc.documentElement) doc.appendChild(doc.createElement('html'));
		if (!doc.head) doc.documentElement.appendChild(doc.createElement('head'));
		if (!doc.body) doc.documentElement.appendChild(doc.createElement('body'));
		// The theme event bubbles (the host listens on window); jsdom never fires a stylesheet
		// link's load, so the event the real applyTheme waits for is dispatched as the
		// convention of tests/settings.test.ts.
		const themed = (): Record<string, unknown> => {
			const link = doc.getElementById('ggs-host-theme') as HTMLLinkElement | null;
			return { href: link?.getAttribute('href') ?? null, html: doc.documentElement.className, body: doc.body.className };
		};
		updateSetting('theme', 'light-modern');
		document.dispatchEvent(new CustomEvent(THEME_EVENT, { bubbles: true }));
		expect(themed()).toMatchObject({ href: '/theme/light-modern.css', html: expect.stringContaining('vscode-light'), body: expect.stringContaining('vscode-light') });
		// The sheet swap announces itself so the view re-mirrors its colour tokens; jsdom
		// cannot fire the link load, so only the swap itself is asserted here.
		updateSetting('theme', 'dark-modern');
		document.dispatchEvent(new CustomEvent(THEME_EVENT, { bubbles: true }));
		expect(themed()).toMatchObject({ href: '/theme/dark-modern.css', html: expect.stringContaining('vscode-dark'), body: expect.stringContaining('vscode-dark') });
	});

	it('delivers the Gerrit states in stages after a pending load', async () => {
		// The backend's first answer pends (the refresh pipeline has not run); the host then
		// refreshes and delivers the fresh states as the extension's staged follow-up responses
		// under the same refresh id: the light part the badges render, then the full states.
		let loads = 0;
		const state = { change: 41466, patchset: 2, codeReview: 2, verified: 0, status: 'new', wip: false, headHash: 'deadbeef', url: null,
			events: [{ type: 'vote', patchset: 2, reviewer: 'R', labels: [{ name: 'Code-Review', value: 2 }], timestamp: 1, raw: 'Patch Set 2', rawFull: 'Patch Set 2' }] };
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			if (message['command'] === 'gerritRefresh') {
				return { command: 'gerritRefresh', error: null, changes: 1, refreshed: true };
			}
			if (message['command'] === 'loadCommits') {
				loads += 1;
				return loads === 1
					? { command: 'loadCommits', refreshId: 7, commits: [], head: 'abc', tags: [], moreCommitsAvailable: false, gerritStates: null, gerritPending: true, error: null }
					: { command: 'loadCommits', refreshId: 7, commits: [], head: 'abc', tags: [], moreCommitsAvailable: false, gerritStates: [state], error: null };
			}
			return { command: message['command'], error: null };
		});
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'loadCommits', repo: 'C:\\repo', refreshId: 7, gerritFetchRefs: true, gerritFetchLimit: null,
			gerritStatusFilter: { new: true, merged: true, abandoned: true, wip: true }
		} } }));
		await vi.waitFor(() => expect(postSpy.mock.calls
			.filter((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse['command'] === 'loadCommits')
			.length).toBe(3));

		// The Gerrit remote and the resolved fetch limit ride along with the requests (the
		// view's own message names neither).
		const calls = backend.callsTo('graph_request').map((call) => call['message'] as Record<string, unknown>);
		expect(calls.find((message) => message['command'] === 'gerritRefresh')).toMatchObject({ repo: 'C:\\repo', gerritRemote: 'origin', gerritFetchLimit: 20 });
		expect(calls.find((message) => message['command'] === 'loadCommits')).toMatchObject({ gerritRemote: 'origin', gerritFetchLimit: 20 });

		const posted = postSpy.mock.calls
			.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
			.filter((message) => message['command'] === 'loadCommits');
		expect(posted[0]!['gerritPending']).toBe(true);
		// Stage 1 - the badges: the states without their event timelines; stage 2 - the full
		// states, which only the review dialog reads. Neither says pending again.
		const light = posted[1]!['gerritStates'] as Record<string, unknown>[];
		expect(light[0]!['events']).toEqual([]);
		expect(light[0]!['eventsPending']).toBe(true);
		expect('gerritPending' in posted[1]!).toBe(false);
		const full = posted[2]!['gerritStates'] as Record<string, unknown>[];
		expect((full[0]!['events'] as unknown[]).length).toBe(1);
		expect('gerritPending' in posted[2]!).toBe(false);
	});

	it('does not run the Gerrit follow-up when the backend\'s answer is not pending', async () => {
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			return { command: message['command'], error: null };
		});
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'loadCommits', repo: 'C:\\repo', refreshId: 1, gerritFetchRefs: false
		} } }));
		await flush(20);
		expect(backend.callsTo('graph_request').some((call) => (call['message'] as Record<string, unknown>)['command'] === 'gerritRefresh')).toBe(false);
	});

	it('defers the uncommitted row off the load and delivers its count as the follow-up', async () => {
		// The load asks the backend for the page without the working-tree scan; once the page is
		// posted, the count is read on its own and the page is repeated with `uncommittedCount`
		// under the same refresh id - the row itself is the view's to synthesise.
		const page = { command: 'loadCommits', refreshId: 5, commits: [{ hash: 'abc', parents: [], author: 'A', email: '', date: 1, message: 'm', heads: [], tags: [], remotes: [], stash: null }], head: 'abc', tags: [], moreCommitsAvailable: false, error: null };
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			if (message['command'] === 'loadCommits') return { ...page, uncommittedPending: true };
			if (message['command'] === 'countUncommittedChanges') return { command: 'countUncommittedChanges', count: 6, error: null };
			return { command: message['command'], error: null };
		});
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'loadCommits', repo: 'C:\\repo', refreshId: 5, maxCommits: 300
		} } }));
		await vi.waitFor(() => expect(postSpy.mock.calls
			.filter((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse['command'] === 'loadCommits')
			.length).toBe(2));

		// The deferred flag rode along with the load, and the count was asked with the
		// configuration's untracked-files setting.
		const sent = backend.callsTo('graph_request').map((call) => call['message'] as Record<string, unknown>);
		expect(sent.find((message) => message['command'] === 'loadCommits')).toMatchObject({ deferUncommittedChanges: true });
		expect(sent.find((message) => message['command'] === 'countUncommittedChanges')).toMatchObject({ repo: 'C:\\repo', includeUntracked: true });

		const posted = postSpy.mock.calls
			.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
			.filter((message) => message['command'] === 'loadCommits');
		expect(posted[0]!['uncommittedPending']).toBe(true);
		expect(posted[1]!['uncommittedCount']).toBe(6);
		expect(posted[1]!['refreshId']).toBe(5);
		expect((posted[1]!['commits'] as unknown[]).length).toBe(1);
	});

	it('asks for no uncommitted count when the page does not show HEAD', async () => {
		// The row hangs off HEAD: a filtered page that cut HEAD out gets no count at all, so no
		// row is ever synthesised above a commit it does not belong to.
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			if (message['command'] === 'loadCommits') {
				return { command: 'loadCommits', refreshId: 9, commits: [{ hash: 'def', parents: [], author: 'A', email: '', date: 1, message: 'm', heads: [], tags: [], remotes: [], stash: null }], head: 'abc', tags: [], moreCommitsAvailable: false, uncommittedPending: true, error: null };
			}
			return { command: message['command'], error: null };
		});
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'loadCommits', repo: 'C:\\repo', refreshId: 9, maxCommits: 300
		} } }));
		await flush(20);
		expect(backend.callsTo('graph_request').some((call) => (call['message'] as Record<string, unknown>)['command'] === 'countUncommittedChanges')).toBe(false);
		expect(postSpy.mock.calls.filter((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse['command'] === 'loadCommits').length).toBe(1);
	});

	it('drops a deferred follow-up that outlived its page (a folder switch remounts the frame)', async () => {
		// The count scan the old page's load scheduled resolves after the frame was remounted onto
		// another repository. The fresh page restarts its refresh-id counter at 0, so the id alone
		// cannot reject the stale completion - the host's load generation must.
		let resolveCount: (() => void) | null = null;
		const page = { command: 'loadCommits', refreshId: 5, commits: [{ hash: 'abc', parents: [], author: 'A', email: '', date: 1, message: 'm', heads: [], tags: [], remotes: [], stash: null }], head: 'abc', tags: [], moreCommitsAvailable: false, error: null };
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			if (message['command'] === 'loadCommits') return { ...page, uncommittedPending: true };
			if (message['command'] === 'countUncommittedChanges') {
				return new Promise((resolve) => {
					resolveCount = () => resolve({ command: 'countUncommittedChanges', count: 6, error: null });
				});
			}
			return { command: message['command'], error: null };
		});
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'loadCommits', repo: 'C:\\repo', refreshId: 5, maxCommits: 300
		} } }));
		await vi.waitFor(() => expect(resolveCount).not.toBeNull());
		host.load('D:\\other'); // the folder switch: the frame remounts, the count's page is gone
		await flush(10);
		resolveCount!();
		await flush(20);
		const posted = postSpy.mock.calls
			.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
			.filter((message) => message['command'] === 'loadCommits');
		expect(posted.length).toBe(1); // only the original page: the stale completion never posted
	});

	it('drops the gerrit stages the same way', async () => {
		let resolveRefresh: (() => void) | null = null;
		const page = { command: 'loadCommits', refreshId: 5, commits: [{ hash: 'abc', parents: [], author: 'A', email: '', date: 1, message: 'm', heads: [], tags: [], remotes: [], stash: null }], head: 'abc', tags: [], moreCommitsAvailable: false, error: null };
		backend.on('graph_request', (args) => {
			const message = args['message'] as Record<string, unknown>;
			if (message['command'] === 'loadCommits') return { ...page, gerritPending: true };
			if (message['command'] === 'gerritRefresh') {
				return new Promise<void>((resolve) => { resolveRefresh = resolve; })
					.then(() => ({ command: 'gerritRefresh', error: null }));
			}
			return { command: message['command'], error: null };
		});
		const host = new GraphHost(delegate);
		document.body.appendChild(host.element);
		host.load('C:\\repo');
		await flush(10);
		const frameWindow = host.frame.contentWindow!;
		const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
		window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
			command: 'loadCommits', repo: 'C:\\repo', refreshId: 5, maxCommits: 300, gerritFetchRefs: true
		} } }));
		await vi.waitFor(() => expect(resolveRefresh).not.toBeNull());
		host.load('D:\\other');
		await flush(10);
		resolveRefresh!();
		await flush(20);
		const posted = postSpy.mock.calls
			.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
			.filter((message) => message['command'] === 'loadCommits');
		expect(posted.length).toBe(1); // no stage response reached the fresh page
		const loads = backend.callsTo('graph_request')
			.map((call) => (call['message'] as Record<string, unknown>)['command']);
		expect(loads.filter((command) => command === 'loadCommits').length).toBe(1); // the stage was never even requested
	});

	it('confirms a zero count across the confirm window before the row drops', async () => {
		vi.useFakeTimers();
		try {
			const counts: number[] = [];
			const page = { command: 'loadCommits', refreshId: 5, commits: [{ hash: 'abc', parents: [], author: 'A', email: '', date: 1, message: 'm', heads: [], tags: [], remotes: [], stash: null }], head: 'abc', tags: [], moreCommitsAvailable: false, error: null };
			backend.on('graph_request', (args) => {
				const message = args['message'] as Record<string, unknown>;
				if (message['command'] === 'loadCommits') return { ...page, uncommittedPending: true };
				if (message['command'] === 'countUncommittedChanges') return { command: 'countUncommittedChanges', count: counts.shift() ?? 0, error: null };
				return { command: message['command'], error: null };
			});
			const host = new GraphHost(delegate);
			document.body.appendChild(host.element);
			host.load('C:\\repo');
			await vi.advanceTimersByTimeAsync(0);
			const frameWindow = host.frame.contentWindow!;
			const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
			const posted = () => postSpy.mock.calls
				.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
				.filter((message) => message['command'] === 'loadCommits');

			// A positive count is delivered at once.
			counts.push(6);
			window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
				command: 'loadCommits', repo: 'C:\\repo', refreshId: 5, maxCommits: 300
			} } }));
			await vi.advanceTimersByTimeAsync(0);
			expect(posted().length).toBe(2);
			expect(posted()[1]!['uncommittedCount']).toBe(6);

			// A refresh that reads a transient zero holds the row: the refresh's own page is
			// posted, but no count completion follows it - and through the whole confirm window
			// the zero is re-read, never delivered.
			counts.push(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
			window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
				command: 'loadCommits', repo: 'C:\\repo', refreshId: 6, maxCommits: 300
			} } }));
			await vi.advanceTimersByTimeAsync(0);
			expect(posted().length).toBe(3);
			expect('uncommittedCount' in posted()[2]!).toBe(false);
			await vi.advanceTimersByTimeAsync(4000);
			expect(posted().length).toBe(3);
			// Once the readings have spanned the window, the confirmed zero lands.
			await vi.advanceTimersByTimeAsync(2000);
			expect(posted().length).toBe(4);
			expect(posted()[3]!['uncommittedCount']).toBe(0);
		} finally {
			vi.useRealTimers();
		}
	});

	it('delivers nothing when the count read keeps failing', async () => {
		vi.useFakeTimers();
		try {
			const page = { command: 'loadCommits', refreshId: 5, commits: [{ hash: 'abc', parents: [], author: 'A', email: '', date: 1, message: 'm', heads: [], tags: [], remotes: [], stash: null }], head: 'abc', tags: [], moreCommitsAvailable: false, error: null };
			backend.on('graph_request', (args) => {
				const message = args['message'] as Record<string, unknown>;
				if (message['command'] === 'loadCommits') return { ...page, uncommittedPending: true };
				if (message['command'] === 'countUncommittedChanges') return { command: 'countUncommittedChanges', count: 0, error: 'status failed' };
				return { command: message['command'], error: null };
			});
			const host = new GraphHost(delegate);
			document.body.appendChild(host.element);
			host.load('C:\\repo');
			await vi.advanceTimersByTimeAsync(0);
			const frameWindow = host.frame.contentWindow!;
			const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
			window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
				command: 'loadCommits', repo: 'C:\\repo', refreshId: 5, maxCommits: 300
			} } }));
			await vi.advanceTimersByTimeAsync(0);
			// The page only: a failed read is "unknown", never a delivered count.
			expect(postedCount(postSpy)).toBe(1);
			// The confirm loop is bounded - it gives up instead of reading forever.
			await vi.advanceTimersByTimeAsync(30000);
			expect(postedCount(postSpy)).toBe(1);
		} finally {
			vi.useRealTimers();
		}
	});

	it('delivers a hard refresh\'s zero count at once, with none of the confirm window a soft refresh would need', async () => {
		// A hard refresh already wiped the rendered row before this pipeline started - there is
		// nothing on screen for a bare zero reading to flicker, so it skips the stabiliser
		// entirely instead of spending the 5s confirm window a soft refresh's zero would.
		vi.useFakeTimers();
		try {
			const page = { command: 'loadCommits', refreshId: 5, commits: [{ hash: 'abc', parents: [], author: 'A', email: '', date: 1, message: 'm', heads: [], tags: [], remotes: [], stash: null }], head: 'abc', tags: [], moreCommitsAvailable: false, error: null };
			backend.on('graph_request', (args) => {
				const message = args['message'] as Record<string, unknown>;
				if (message['command'] === 'loadCommits') return { ...page, uncommittedPending: true };
				if (message['command'] === 'countUncommittedChanges') return { command: 'countUncommittedChanges', count: 0, error: null };
				return { command: message['command'], error: null };
			});
			const host = new GraphHost(delegate);
			document.body.appendChild(host.element);
			host.load('C:\\repo');
			await vi.advanceTimersByTimeAsync(0);
			const frameWindow = host.frame.contentWindow!;
			const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
			window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
				command: 'loadCommits', repo: 'C:\\repo', refreshId: 5, maxCommits: 300, hard: true
			} } }));
			// No timer advance beyond the microtask queue: a soft refresh's zero would still be
			// sitting in the confirm window here (see the test above), holding the row unposted.
			await vi.advanceTimersByTimeAsync(0);
			expect(postedCount(postSpy)).toBe(2);
			const posted = postSpy.mock.calls
				.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
				.filter((message) => message['command'] === 'loadCommits');
			expect(posted[1]!['uncommittedCount']).toBe(0);
		} finally {
			vi.useRealTimers();
		}
	});

	it('delivers nothing for a hard refresh whose count read fails, instead of a wrong zero', async () => {
		vi.useFakeTimers();
		try {
			const page = { command: 'loadCommits', refreshId: 5, commits: [{ hash: 'abc', parents: [], author: 'A', email: '', date: 1, message: 'm', heads: [], tags: [], remotes: [], stash: null }], head: 'abc', tags: [], moreCommitsAvailable: false, error: null };
			backend.on('graph_request', (args) => {
				const message = args['message'] as Record<string, unknown>;
				if (message['command'] === 'loadCommits') return { ...page, uncommittedPending: true };
				if (message['command'] === 'countUncommittedChanges') return { command: 'countUncommittedChanges', count: 0, error: 'status failed' };
				return { command: message['command'], error: null };
			});
			const host = new GraphHost(delegate);
			document.body.appendChild(host.element);
			host.load('C:\\repo');
			await vi.advanceTimersByTimeAsync(0);
			const frameWindow = host.frame.contentWindow!;
			const postSpy = vi.spyOn(frameWindow, 'postMessage').mockImplementation(() => undefined);
			window.dispatchEvent(new MessageEvent('message', { source: frameWindow, data: { __studioGraphRequest: {
				command: 'loadCommits', repo: 'C:\\repo', refreshId: 5, maxCommits: 300, hard: true
			} } }));
			await vi.advanceTimersByTimeAsync(0);
			// The page only: a failed read on a hard refresh gives up at once (no confirm loop to
			// bound, since the hard path never enters it) rather than delivering a false zero.
			expect(postedCount(postSpy)).toBe(1);
			await vi.advanceTimersByTimeAsync(30000);
			expect(postedCount(postSpy)).toBe(1);
		} finally {
			vi.useRealTimers();
		}
	});
});

function postedCount(postSpy: ReturnType<typeof vi.spyOn>): number {
	return postSpy.mock.calls
		.map((call) => (call[0] as { __studioGraphResponse: Record<string, unknown> }).__studioGraphResponse)
		.filter((message) => message['command'] === 'loadCommits').length;
}
